---
name: Debug-Mixin
version: 0.4.4
author:
  - 'Khemir Nadim ibn Hamouda. <nadim@khemir.net>'
abstract: Make your applications and modules easier to debug
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Data::Compare: 0
  Data::TreeDumper: 0
  List::MoreUtils: 0
  Readonly: 0
  Sub::Install: 0
  Test::Output: 0
  Tie::Hash::Indexed: 0
build_requires:
  Test::Block: 0
  Test::Exception: 0
  Test::NoWarnings: 0
  Test::Output: 0
  Test::Warn: 0
  Text::Diff: 0
provides:
  Debug::Mixin:
    file: lib/Debug/Mixin.pm
    version: 0.4
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
